### PR TITLE
Added a new pyhon class linkedin-api.py, edited to allow to search only jobs with easyApply easly.

### PR DESCRIPTION
**Pull request by spectreDeveloper**
You can call the LinkedInEvolvedAPI class api, to use a overrided method search_jobs, to search job having filter easyApply as boolean

### CODE REVIEW

**Review by ralyodio — APPROVED** [review]
LGTM

**Comment by spectreDeveloper** [comment]
usage example:
```bash 
    if __name__ == '__main__':
        api = LinkedInEvolvedAPI('username', 'password')
        jobs = api.search_jobs('Software Engineer',easy_apply=True,limit=5)
        for job in jobs:
            jobs_id: str = job['job_id']`
            print(job)
```

**Comment by spectreDeveloper** [comment]
i ve missed to add as requirements, i will push another PR to add in the file, srry.

**Comment by spectreDeveloper** [comment]
wrong branch.

check the v3.

**Pull request closed without merging**
