### PR TITLE
Adding an Adapter fr 

### PR DESCRIPTION
**Pull request by raeeceip**
# AI Model Integration and Performance Enhancements for LinkedIn_AIHawk

## Introduction

Hi there! I'm Chiso, a software engineer passionate about automation and AI. I've forked this repo and made some contributions to enhance its functionality and performance. I'm excited to share these updates with the community and look forward to your feedback!

## Changes Made

1. **Multi-AI Model Support**
   - Implemented `ai_adapter.py` to support OpenAI, Claude, and Gemini models.
   - Created an `AIAdapter` class for easy switching between AI providers.

2. **Claude Integration Fix**
   - Updated `ClaudeModel` class to correctly format prompts for Claude's API.

3. **GPTAnswerer Improvements**
   - Refactored to use the new `AIAdapter` for generating responses.
   - Enhanced prompt structures for better context across all methods.

4. **Configuration Updates**
   - Added `ai_model` field in `secrets.yaml` for AI provider selection.
   - Updated `config.yaml` to align with job search preferences.

5. **Main Script Updates**
   - Modified `main.py` to handle new AI model configuration and initialization.

## Ongoing Performance Improvements

We're working on:
- Optimizing job search algorithms
- Implementing caching for AI responses
- Enhancing browser automation
- Improving API usage efficiency

## Open for Review

I'd love to get your thoughts on these changes:
- Are there any areas that need further clarification?
- Do you see any potential issues with the new AI adapter implementation?
- Any suggestions for additional performance improvements?

Your insights are valuable, and I'm open to making further adjustments based on your feedback. Let's make LinkedIn_AIHawk even better together!

Thanks for your time and consideration!

Best regards,
Chiso

### CODE REVIEW

**Comment by feder-cr** [comment]
hello, I like the idea very much but I am not very sure about the design you thought of, we should think about it a little more.

join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by feder-cr** [comment]
hi @raeeceip I don't like the idea of adding fields to secrets, I'm afraid it will become complicated for users to understand

**Comment by raeeceip** [comment]
I agree, it would make it simpler for users. Also I apologize , I have been
busy with some other work so I haven't commented into he telegram
repository, but will modify to your requests! Feel free to leave any more
changes you would like to see

**Comment by feder-cr** [comment]
@raeeceip please work here https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/tree/v2

**Pull request closed without merging**
