### PR TITLE
Add support for Hugging Face API

### PR DESCRIPTION
**Pull request by kardSIM**
I discovered this project through the Reddit post and found it to be an excellent initiative. 
I have made some modifications by adding support for the use of open-source models available on Hugging Face. 
"tiiuae/falcon-7b-instruct" model was used in the script.
Please review the changes and let me know if there are any improvements or adjustments needed.

### CODE REVIEW

**Comment by feder-cr** [comment]
One must:
1) make it more moudlare maybe trmiate the use of a parent class.
2) make it more user friendly
@kardSIM

**Comment by kardSIM** [comment]
its done 

to run the script with hugging face api use    "python main.py --opensource"

**Comment by kardSIM** [comment]
Hi,

I noticed that this pull request was closed, and I wanted to understand the reason behind it .

**Comment by Durgeshhirani** [comment]
@kardSIM  Hi, I wanted to use hugging face api in this. Can you provide your updated model or help me in this ?

**Comment by feder-cr** [comment]
@kardSIM if you want, you can add this on v3

**Comment by feder-cr** [comment]
@kardSIM we already have the structure for new models

**Comment by Durgeshhirani** [comment]
how to use it with hugging face phi3 model ? I am trying for last 2 days and it's not working at all.

> @kardSIM we already have the structure for new models

**Comment by feder-cr** [comment]
@kardSIM ?

**Comment by kardSIM** [comment]
I will try to look on it next weekend

**Pull request closed without merging**
