### PR TITLE
handled already logined case

### PR DESCRIPTION
**Pull request by riteshp112**

### CODE REVIEW

**Comment by feder-cr** [comment]
@riteshp112 please try explain

**Comment by riteshp112** [comment]
If the user is already logged in the login page redirects to https://www.linkedin.com/feed/ so we can skip login in that case.

**Comment by feder-cr** [comment]
@riteshp112  right now at me works perfectly, why should i accept this merge, let me understand when a bug occurs

**Comment by riteshp112** [comment]
Because if you quick rerun the code it expects the first screen to be the login page and gives an error.

**Comment by riteshp112** [comment]
👍

**Pull request merged**
