### PR TITLE
Adding Google Gemini Implementation

### PR DESCRIPTION
**Pull request by khalid-faiz**
Added GeminiModel class with its import, updated requirements.txt and README.txt.

### CODE REVIEW

**Comment by air55555** [comment]
@khalid-faiz great work , could you please provide some artifacts - test logs , generated failes , etc

**Comment by khalid-faiz** [comment]
@air55555 Should I share the output folder?

**Comment by khalid-faiz** [comment]
@air55555  here are the output files, I hope this is what you are after
[failed.json](https://github.com/user-attachments/files/16940790/failed.json)
[open_ai_calls.json](https://github.com/user-attachments/files/16940791/open_ai_calls.json)
[skipped.json](https://github.com/user-attachments/files/16940792/skipped.json)
[skipped_due_to_applicants.json](https://github.com/user-attachments/files/16940793/skipped_due_to_applicants.json)
[success.json](https://github.com/user-attachments/files/16940794/success.json)

**Comment by air55555** [comment]
@khalid-faiz  thanks ! we re interested especially in gemini interaction log. How successful it was ? comparison with open ai ?

**Comment by khalid-faiz** [comment]
@air55555 I can't compare the two because I didn't use it with open ai, but it is more seamless than the implementation I did at the beginning (from the `main` branch), the `v3` branch is much more modular.

**Pull request merged**
