### PR TITLE
added timestamp while logging jobs

### PR DESCRIPTION
**Pull request by parth-savjani**
Added timestamp while logging job details to log files like skipped.json, success.json and failed.json

### CODE REVIEW

**Comment by air55555** [comment]
Will this add much more ux?

**Comment by parth-savjani** [comment]
Actually, I ran app every day so having timestamps helped me analyse logs and manually apply for failed jobs.

**Comment by air55555** [comment]
Maybe you can improve this by adding standalone func/app that filters failed jobs to file for easing of applying manually?

**Comment by parth-savjani** [comment]
Logs are getting appended to the same file so It's hard to figure out the starting point without a timestamp.

**Comment by air55555** [comment]
Correct, so could you add really great ux filtering python module/func to let Community use your improvement properly?

**Comment by feder-cr** [comment]
@parth-savjani please use V3

**Pull request closed without merging**
