### PR TITLE
add: apply_to_job func init struct

### PR DESCRIPTION
**Pull request by omar-zr**

### CODE REVIEW

**Comment by feder-cr** [comment]
@omar-zr please explain

**Comment by omar-zr** [comment]
This implementation includes:

1. Fetching the fields required for the application using get_fields_for_easy_apply.
2. Prompting the user to input data for each field (for testing purposes).
3. Building the payload with the filled fields.
4. Sending the payload to apply for the job.

Note: This implementation uses input()  we have to replace it with input from the AI that we will use

**Comment by air55555** [comment]
Are there any issues with existing structure?

**Comment by omar-zr** [comment]
@air55555  Sorry  I didn't know that apply_to_job fucn been implemented before can you pointed to me ?!

**Comment by spectreDeveloper** [comment]
@feder-cr close this PR, have issue regarding functions for apply

**Pull request closed without merging**
