### PR TITLE
improving validate_yaml_file function in main.py

### PR DESCRIPTION
**Pull request by sundarmd**
The suggested change improves the `validate_yaml_file` function in a few key ways:

1. Use of context manager:
   The new version uses a `with` statement to open the file, which ensures that the file is properly closed after reading, even if an exception occurs. This is a best practice for file handling in Python.

2. Combined exception handling:
   The original version had separate `except` blocks for `yaml.YAMLError` and `FileNotFoundError`. The new version combines these into a single `except` clause, which simplifies the error handling.

3. More specific error message:
   The new version includes the specific exception message in the `ConfigError` that's raised, which can provide more detailed information about what went wrong.

4. Consistent return:
   The function now always either returns the loaded YAML data or raises a `ConfigError`. This makes the function's behavior more predictable.

These changes make the function more concise, easier to read, and slightly more efficient in terms of resource management (due to the use of the context manager). It also provides more informative error messages, which can be helpful for debugging.

### CODE REVIEW

**Comment by feder-cr** [comment]
@sundarmd please on V3 and join on telegram group

**Comment by feder-cr** [comment]
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by sundarmd** [comment]
created the PR on V3 and joined the TG group ;)

**Comment by sundarmd** [comment]
closing this PR on main branch because opened it on V3

**Comment by feder-cr** [comment]
@sundarmd i see pnly 2 line canghed

**Comment by sundarmd** [comment]
yes.
are you against merging this PR?

**Comment by feder-cr** [comment]
@sundarmd yes, because i dont understand what change

**Pull request closed without merging**
