### PR TITLE
Update gpt.py

### PR DESCRIPTION
**Pull request by rishabhraj1572**
changes : now no need of openai api keys

### CODE REVIEW

**Comment by shivamkrsarin1996** [comment]
Could you tell the 'after' behavior if open AI API is not required? 
Usually a 'before' and 'after' helps in understanding that

**Comment by rishabhraj1572** [comment]
> Could you tell the 'after' behavior if open AI API is not required? Usually a 'before' and 'after' helps in understanding that

before : we need open ai api key and it is paid
after : used alternate hosted free api which is also powered by chatgpt api (works same but free)

**Comment by feder-cr** [comment]
@rishabhraj1572 join on telegram

**Comment by air55555** [comment]
@rishabhraj1572  , the link is https://t.me/+-ybq6H0yW6FiOTk0

**Review by air55555 — CHANGES_REQUESTED** [review]
@rishabhraj1572  we need more flexibility in case api url will be changed, along with model name . These shouldnt be hardcoded

**Comment by shivamkrsarin1996** [comment]
> > Could you tell the 'after' behavior if open AI API is not required? Usually a 'before' and 'after' helps in understanding that
> 
> 
> 
> before : we need open ai api key and it is paid
> 
> after : used alternate hosted free api which is also powered by chatgpt api (works same but free)

Do we need to make any additional changes? 
I tried updating the API key but still got the 'credit expired' message with it trying to scan all the jobs but doesn't apply for the roles

**Pull request closed without merging**
