### PR TITLE
plain_text_resume.yaml generator from text resume

### PR DESCRIPTION
**Pull request by mmcc007**
- convert your resume to a text file
- run the utility to generate the plain_text_resume.yaml from your resume.
- mentioned in #163

### CODE REVIEW

**Comment by josylad** [comment]
Just wondering if the time used to convert to text can't be used to convert to yaml directly. 

Now, I have to convert my Pdf resume to text before converting to yaml and then review the yaml for correctness again. It seems like a longer loop. 

Just saying.

**Comment by air55555** [comment]
@mmcc007 thank you for your hard work! Could you pls make pr to v3 as stated in the tg dev group pinned message ?

**Comment by mmcc007** [comment]
@air55555 No probs. I have changed the PR to merge to v3 instead of main. In the process I merged my main to your v3. Check requirements.txt is ok. It should have the linkedin api as well as all the other stuff from main (afaik).

**Comment by mmcc007** [comment]
@josylad Adding support for various file formats (pdf, docx, etc) would be an enhancement. I tried doing it all in one call (using the pdf), but it was exceeding the context lenght (8k?). Converting to txt was an easy way to solve the problem to get something working.

**Comment by josylad** [comment]
> @josylad Adding support for various file formats (pdf, docx, etc) would be an enhancement. I tried doing it all in one call (using the pdf), but it was exceeding the context lenght (8k?). Converting to txt was an easy way to solve the problem to get something working.

Ok, noted.

**Comment by feder-cr** [comment]
@mmcc007 it would be nice to also be able to do from old_cv.pdf to plain_text_resume.yaml

**Comment by mmcc007** [comment]
> @mmcc007 it would be nice to also be able to do from old_cv.pdf to plain_text_resume.yaml

@feder-cr done locally using a lib

**Pull request merged**
